runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: 'example-gcs-bucket'

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: always
    redirect_http_respones_code: 301
    script: auto
